# Application Config
spring.application.name=phishing-detector
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Auth0 Configuration
spring.security.oauth2.client.registration.auth0.client-id=cBmn6qryUPKDh9x6tmCozG4y3uzprj4u
spring.security.oauth2.client.registration.auth0.client-secret=oKS_K_d3YXi1JwyO0bQsv3IG0jsD_Lir99yuRcKdIzeIA9JAB3BoFen3vXPAl7Q4
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.client-name=Auth0

# Auth0 Provider Configuration
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-eyz4r1204za77l53.us.auth0.com/
spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-eyz4r1204za77l53.us.auth0.com/authorize?prompt=login

spring.security.oauth2.client.provider.auth0.token-uri=https://dev-eyz4r1204za77l53.us.auth0.com/oauth/token
spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-eyz4r1204za77l53.us.auth0.com/userinfo
spring.security.oauth2.client.provider.auth0.jwk-set-uri=https://dev-eyz4r1204za77l53.us.auth0.com/.well-known/jwks.json

# Resource Server Configuration (for API protection)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-eyz4r1204za77l53.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://phishing-detector-api

# Groq LLM Configuration
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant